import { useEffect, useRef, useState } from 'react';
import Modal from '../common/Modal';
import AlertMessage from '../common/AlertMessage';
import Spinner from '../common/Spinner';
import {
  previewCustomerImport,
  runCustomerImport,
  downloadCustomerImportTemplate
} from '../../services/customerService';

const MAX_PREVIEW_ROWS = 100;

const STATUS_BADGE = {
  VALID: 'text-bg-success',
  INVALID: 'text-bg-danger',
  DUPLICATE: 'text-bg-warning'
};

const STATUS_LABEL = {
  VALID: 'Will import',
  INVALID: 'Rejected',
  DUPLICATE: 'Duplicate — skipped'
};

/**
 * Bulk customer import: upload, preview, confirm, summary.
 *
 * Nothing here decides what is valid. The file is sent to the backend, which
 * parses and validates it with the same rules the single-customer form uses and
 * returns the verdict per row; this component only displays it. Confirming
 * sends the same file again to the import endpoint, which re-validates from
 * scratch — the preview is information, never an instruction.
 */
export default function CustomerImportModal({ open, onClose, onImported }) {
  const inputRef = useRef(null);

  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    if (!open) return;
    setFile(null);
    setPreview(null);
    setResult(null);
    setBusy('');
    setError('');
    if (inputRef.current) inputRef.current.value = '';
  }, [open]);

  const handleTemplate = async () => {
    setError('');
    setBusy('template');
    try {
      await downloadCustomerImportTemplate();
    } catch (requestError) {
      setError(requestError.message || 'The template could not be downloaded.');
    } finally {
      setBusy('');
    }
  };

  const handleFile = async (event) => {
    const chosen = event.target.files?.[0] ?? null;
    setFile(chosen);
    setPreview(null);
    setResult(null);
    setError('');
    if (!chosen) return;

    setBusy('preview');
    try {
      const response = await previewCustomerImport(chosen);
      setPreview(response.data);
    } catch (requestError) {
      // The backend explains what is wrong with the file; it is shown as-is.
      setError(requestError.message || 'That file could not be read.');
      setPreview(null);
    } finally {
      setBusy('');
    }
  };

  const handleImport = async () => {
    if (!file) return;
    setError('');
    setBusy('import');
    try {
      const response = await runCustomerImport(file);
      setResult(response.data);
      setPreview(null);
      await onImported?.(response.data);
    } catch (requestError) {
      setError(requestError.message || 'The import could not be completed.');
    } finally {
      setBusy('');
    }
  };

  const summary = preview?.summary ?? result?.summary ?? null;
  const rows = preview?.rows ?? [];
  const canImport = Boolean(file) && (summary?.validRows ?? 0) > 0 && !busy && !result;

  return (
    <Modal title="Bulk import customers" open={open} onClose={busy ? () => {} : onClose} size="modal-xl">
      <div className="modal-body">
        <AlertMessage message={error} onDismiss={() => setError('')} />

        <div className="d-flex flex-wrap align-items-end justify-content-between gap-3 mb-3">
          <div className="flex-grow-1">
            <label className="form-label small fw-semibold" htmlFor="customer-import-file">
              Excel file (.xlsx)
            </label>
            <input
              id="customer-import-file"
              ref={inputRef}
              type="file"
              accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
              className="form-control"
              onChange={handleFile}
              disabled={Boolean(busy)}
            />
            <div className="form-text">
              Use the template. CIFIDs are generated by the system — a file containing a CIFID column is refused.
            </div>
          </div>
          <button type="button" className="btn btn-outline-secondary" onClick={handleTemplate} disabled={Boolean(busy)}>
            <i className="bi bi-download me-2" aria-hidden="true" />
            {busy === 'template' ? 'Preparing…' : 'Download template'}
          </button>
        </div>

        {busy === 'preview' ? <Spinner label="Checking the file…" /> : null}
        {busy === 'import' ? <Spinner label="Importing customers…" /> : null}

        {summary ? (
          <div className={`alert ${result ? 'alert-success' : summary.validRows > 0 ? 'alert-info' : 'alert-warning'}`}>
            <div className="row g-2 small text-center">
              <div className="col-6 col-md">
                <div className="text-uppercase fw-semibold">Total rows</div>
                <div className="fw-bold fs-5">{summary.totalRows}</div>
              </div>
              <div className="col-6 col-md">
                <div className="text-uppercase fw-semibold">Valid</div>
                <div className="fw-bold fs-5">{summary.validRows}</div>
              </div>
              <div className="col-6 col-md">
                <div className="text-uppercase fw-semibold">Invalid</div>
                <div className="fw-bold fs-5">{summary.invalidRows}</div>
              </div>
              <div className="col-6 col-md">
                <div className="text-uppercase fw-semibold">Duplicates</div>
                <div className="fw-bold fs-5">{summary.duplicateRows}</div>
              </div>
              <div className="col-6 col-md">
                <div className="text-uppercase fw-semibold">Imported</div>
                <div className="fw-bold fs-5">{summary.importedRows}</div>
              </div>
            </div>
            {summary.blankRows > 0 ? (
              <div className="small mt-2">{summary.blankRows} empty row(s) were ignored.</div>
            ) : null}
            {!result ? (
              <div className="small mt-2">
                Nothing has been saved yet — this is a preview. Only the valid rows will be imported.
              </div>
            ) : null}
          </div>
        ) : null}

        {result ? (
          <>
            <h3 className="h6 fw-bold">Imported customers</h3>
            <div className="table-responsive" style={{ maxHeight: '18rem' }}>
              <table className="table table-sm align-middle mb-0">
                <thead className="table-light">
                  <tr>
                    <th scope="col">CIFID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Mobile</th>
                  </tr>
                </thead>
                <tbody>
                  {result.imported.map((customer) => (
                    <tr key={customer.cifId}>
                      <td className="font-monospace">{customer.cifId}</td>
                      <td>{customer.fullName}</td>
                      <td className="font-monospace">{customer.mobile}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {result.errors.length > 0 ? (
              <p className="form-text mb-0 mt-2">
                {result.errors.length} row problem(s) were skipped and not imported. Fix them in the file and upload it
                again — the imported rows above will be reported as duplicates and skipped.
              </p>
            ) : null}
          </>
        ) : null}

        {rows.length > 0 ? (
          <>
            <h3 className="h6 fw-bold">Rows</h3>
            <div className="table-responsive" style={{ maxHeight: '22rem' }}>
              <table className="table table-sm align-middle mb-0">
                <thead className="table-light">
                  <tr>
                    <th scope="col">Excel row</th>
                    <th scope="col">Name</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Status</th>
                    <th scope="col">Problems</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.slice(0, MAX_PREVIEW_ROWS).map((row) => (
                    <tr key={row.rowNumber}>
                      <td className="fw-semibold">{row.rowNumber}</td>
                      <td>{[row.values.firstName, row.values.middleName, row.values.lastName].filter(Boolean).join(' ') || '—'}</td>
                      <td className="font-monospace">{row.values.mobile ?? '—'}</td>
                      <td>
                        <span className={`badge ${STATUS_BADGE[row.status] ?? 'text-bg-secondary'}`}>
                          {STATUS_LABEL[row.status] ?? row.status}
                        </span>
                      </td>
                      <td className="small">
                        {row.errors.length === 0
                          ? '—'
                          : row.errors.map((problem, index) => (
                              <div key={`${row.rowNumber}-${problem.field}-${index}`}>
                                <span className="fw-semibold">{problem.field}</span>: {problem.reason}
                              </div>
                            ))}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {rows.length > MAX_PREVIEW_ROWS ? (
              <p className="form-text mb-0">
                Showing the first {MAX_PREVIEW_ROWS} of {rows.length} rows. All of them are checked, and all valid rows
                are imported.
              </p>
            ) : null}
          </>
        ) : null}
      </div>

      <div className="modal-footer">
        <button type="button" className="btn btn-outline-secondary" onClick={onClose} disabled={Boolean(busy)}>
          {result ? 'Close' : 'Cancel'}
        </button>
        {!result ? (
          <button type="button" className="btn btn-primary" onClick={handleImport} disabled={!canImport}>
            {busy === 'import' ? (
              <>
                <span className="spinner-border spinner-border-sm me-2" aria-hidden="true" />
                Importing…
              </>
            ) : (
              `Import ${summary?.validRows ?? 0} customer${(summary?.validRows ?? 0) === 1 ? '' : 's'}`
            )}
          </button>
        ) : null}
      </div>
    </Modal>
  );
}
