import { useEffect, useState } from 'react';
import Modal from '../common/Modal';
import AlertMessage from '../common/AlertMessage';
import { createRoute, updateRoute } from '../../services/routeService';
import { toFieldErrors } from '../../utils/errorHandler';

const EMPTY = { name: '', description: '' };

/**
 * Create/edit dialog for a route.
 *
 * Only name and description are editable. The route code is generated by the
 * backend and is immutable, so it is displayed read-only in edit mode and has
 * no input at all in create mode.
 */
export default function RouteFormModal({ open, mode = 'create', route = null, onClose, onSaved }) {
  const [form, setForm] = useState(EMPTY);
  const [fieldErrors, setFieldErrors] = useState({});
  const [formError, setFormError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!open) return;
    setForm(mode === 'edit' && route ? { name: route.name ?? '', description: route.description ?? '' } : EMPTY);
    setFieldErrors({});
    setFormError('');
  }, [open, mode, route]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
    setFieldErrors((current) => ({ ...current, [name]: undefined }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setFormError('');

    const errors = {};
    if (!form.name.trim()) errors.name = 'Route name is required';
    else if (form.name.trim().length > 120) errors.name = 'Route name must be at most 120 characters';
    if (form.description.length > 255) errors.description = 'Description must be at most 255 characters';

    if (Object.keys(errors).length > 0) {
      setFieldErrors(errors);
      return;
    }

    setSubmitting(true);
    try {
      // Sent as an empty string rather than omitted, so an existing description
      // can actually be cleared — the backend maps blank to null.
      const payload = { name: form.name.trim(), description: form.description.trim() };
      const response = mode === 'create' ? await createRoute(payload) : await updateRoute(route.id, payload);
      onSaved({ mode, route: response.data.route });
    } catch (error) {
      setFormError(error.message);
      setFieldErrors(toFieldErrors(error));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Modal title={mode === 'create' ? 'New route' : 'Edit route'} open={open} onClose={submitting ? () => {} : onClose}>
      <form onSubmit={handleSubmit} noValidate>
        <div className="modal-body">
          <AlertMessage message={formError} onDismiss={() => setFormError('')} />

          {mode === 'edit' ? (
            <div className="d-flex align-items-center gap-2 mb-3 pb-3 border-bottom">
              <span className="text-secondary small">Route code</span>
              <span className="badge text-bg-light border font-monospace">{route?.routeCode}</span>
              <span className="text-secondary small">· system generated, cannot be changed</span>
            </div>
          ) : (
            <p className="text-secondary small">A route code is generated automatically when the route is saved.</p>
          )}

          <div className="mb-3">
            <label className="form-label small fw-semibold" htmlFor="route-name">
              Name <span className="text-danger">*</span>
            </label>
            <input
              id="route-name"
              name="name"
              className={`form-control${fieldErrors.name ? ' is-invalid' : ''}`}
              value={form.name}
              onChange={handleChange}
              disabled={submitting}
              autoFocus
              maxLength={120}
            />
            <div className="invalid-feedback">{fieldErrors.name}</div>
          </div>

          <div className="mb-0">
            <label className="form-label small fw-semibold" htmlFor="route-description">
              Description
            </label>
            <textarea
              id="route-description"
              name="description"
              rows={2}
              className={`form-control${fieldErrors.description ? ' is-invalid' : ''}`}
              value={form.description}
              onChange={handleChange}
              disabled={submitting}
              maxLength={255}
            />
            <div className="invalid-feedback">{fieldErrors.description}</div>
          </div>
        </div>

        <div className="modal-footer">
          <button type="button" className="btn btn-outline-secondary" onClick={onClose} disabled={submitting}>
            Cancel
          </button>
          <button type="submit" className="btn btn-primary" disabled={submitting}>
            {submitting ? (
              <>
                <span className="spinner-border spinner-border-sm me-2" aria-hidden="true" />
                Saving…
              </>
            ) : mode === 'create' ? (
              'Create route'
            ) : (
              'Save changes'
            )}
          </button>
        </div>
      </form>
    </Modal>
  );
}
