'use strict';

const { body, param, query } = require('express-validator');
const {
  LEDGER_TYPE_VALUES,
  COLLECTION_STATUS_VALUES,
  MAX_ALLOCATIONS_PER_COLLECTION
} = require('../config/collections');

const idParamRule = param('id').isInt({ min: 1 }).withMessage('A valid collection id is required');

/** Rejects "1e5", "Infinity", negatives and more than two decimal places. */
const moneyRule = (field, label) =>
  body(field)
    .exists()
    .withMessage(`${label} is required`)
    .bail()
    .custom((value) => /^\d+(\.\d{1,2})?$/.test(String(value)))
    .withMessage(`${label} must be a plain number with at most 2 decimal places`)
    .bail()
    .custom((value) => Number(value) > 0)
    .withMessage(`${label} must be greater than zero`);

/**
 * Everything about an instalment is derived from the allocation ledger.
 * Rejecting these outright keeps the collection API from being a back door into
 * EMI state.
 */
const backendControlledRules = [
  body('collectionNumber').not().exists().withMessage('The collection number is generated by the system'),
  body('status').not().exists().withMessage('A new collection is always POSTED'),
  body('createdBy').not().exists().withMessage('createdBy is set by the system'),
  body('updatedBy').not().exists().withMessage('updatedBy is set by the system'),
  body('id').not().exists().withMessage('id is set by the system'),
  body('emiStatus').not().exists().withMessage('EMI status is derived from the allocation ledger'),
  body('dpd').not().exists().withMessage('DPD is calculated by the system'),
  body('outstanding').not().exists().withMessage('Outstanding is derived from the allocation ledger'),
  body('paymentDate').not().exists().withMessage('Payment dates are derived from the allocation ledger'),
  body('amountCollected').not().exists().withMessage('Collected amounts are derived from the allocation ledger')
];

const createCollectionRules = [
  body('loanId').exists().withMessage('A loan is required').bail().isInt({ min: 1 }).withMessage('loanId must be a positive integer'),
  body('customerId')
    .exists()
    .withMessage('A paying customer is required')
    .bail()
    .isInt({ min: 1 })
    .withMessage('customerId must be a positive integer'),
  moneyRule('amount', 'Collection amount'),
  body('collectionDate').notEmpty().withMessage('Collection date is required').bail().isISO8601().withMessage('Collection date must be a valid date (YYYY-MM-DD)'),
  body('ledgerType')
    .notEmpty()
    .withMessage('Ledger type is required')
    .bail()
    .isIn(LEDGER_TYPE_VALUES)
    .withMessage(`Ledger type must be one of: ${LEDGER_TYPE_VALUES.join(', ')}`),
  body('paymentReference').optional({ values: 'null' }).isString().withMessage('Payment reference must be text').bail().trim().isLength({ max: 120 }).withMessage('Payment reference is too long'),
  body('notes').optional({ values: 'null' }).isString().withMessage('Notes must be text').bail().trim().isLength({ max: 500 }).withMessage('Notes are too long'),

  body('allocations')
    .isArray({ min: 1, max: MAX_ALLOCATIONS_PER_COLLECTION })
    .withMessage(`Provide between 1 and ${MAX_ALLOCATIONS_PER_COLLECTION} allocations`),
  body('allocations.*.emiId').exists().withMessage('Each allocation needs an emiId').bail().isInt({ min: 1 }).withMessage('emiId must be a positive integer'),
  body('allocations.*.amount')
    .exists()
    .withMessage('Each allocation needs an amount')
    .bail()
    .custom((value) => /^\d+(\.\d{1,2})?$/.test(String(value)) && Number(value) > 0)
    .withMessage('Each allocation amount must be a positive number with at most 2 decimal places'),

  ...backendControlledRules
];

const reverseCollectionRules = [
  idParamRule,
  body('reason').optional({ values: 'falsy' }).isString().withMessage('Reason must be text').bail().trim().isLength({ max: 300 }).withMessage('Reason is too long'),
  body('status').not().exists().withMessage('Use this endpoint to reverse; status is set by the system')
];

const collectionIdRules = [idParamRule];

const listCollectionsRules = [
  query('page').optional().isInt({ min: 1 }).withMessage('page must be a positive integer'),
  query('limit').optional().isInt({ min: 1, max: 100 }).withMessage('limit must be between 1 and 100'),
  query('search').optional().isString().trim().isLength({ max: 120 }).withMessage('search is too long'),
  query('status').optional().isIn(COLLECTION_STATUS_VALUES).withMessage(`status must be one of: ${COLLECTION_STATUS_VALUES.join(', ')}`),
  query('ledgerType').optional().isIn(LEDGER_TYPE_VALUES).withMessage(`ledgerType must be one of: ${LEDGER_TYPE_VALUES.join(', ')}`),
  query('loanId').optional().isInt({ min: 1 }).withMessage('loanId must be a positive integer'),
  query('createdBy').optional().isInt({ min: 1 }).withMessage('createdBy must be a positive integer'),
  query('dateFrom').optional().isISO8601().withMessage('dateFrom must be a valid date'),
  query('dateTo').optional().isISO8601().withMessage('dateTo must be a valid date'),
  query('sortBy')
    .optional()
    .isIn(['collectionNumber', 'amount', 'collectionDate', 'status', 'createdAt'])
    .withMessage('sortBy is not a sortable field'),
  query('sortOrder').optional().isIn(['ASC', 'DESC', 'asc', 'desc']).withMessage('sortOrder must be ASC or DESC')
];

const loanSummaryRules = [param('loanId').isInt({ min: 1 }).withMessage('A valid loan id is required')];

module.exports = {
  createCollectionRules,
  reverseCollectionRules,
  collectionIdRules,
  listCollectionsRules,
  loanSummaryRules
};
