'use strict';

const { body, param, query } = require('express-validator');
const { isValidMobile } = require('../utils/mobile');
const { CUSTOMER_STATUS_VALUES, GENDER_VALUES, MARITAL_STATUS_VALUES } = require('../config/customers');

const idParamRule = param('id').isInt({ min: 1 }).withMessage('A valid customer id is required');

/** Optional free-text field: present-but-empty is treated as "not supplied". */
const optionalText = (field, max, label) =>
  body(field).optional({ values: 'falsy' }).isString().withMessage(`${label} must be text`).bail().trim().isLength({ max }).withMessage(`${label} must be at most ${max} characters`);

const mobileRule = (field, label, optional) => {
  const chain = optional ? body(field).optional({ values: 'falsy' }) : body(field).notEmpty().withMessage(`${label} is required`).bail();
  return chain
    .custom((value) => isValidMobile(value))
    .withMessage(`${label} must be a valid 10-digit Indian mobile number (with or without +91)`);
};

/**
 * Fields the backend owns. Rejecting them explicitly turns a silent no-op into
 * a clear 422, which matters most for cif_id — it is immutable by design.
 */
const backendControlledRules = [
  body('cifId').not().exists().withMessage('CIFID is generated by the system and cannot be set or changed'),
  body('cif_id').not().exists().withMessage('CIFID is generated by the system and cannot be set or changed'),
  body('fullName').not().exists().withMessage('Full name is derived from the name fields'),
  body('createdBy').not().exists().withMessage('createdBy is set by the system'),
  body('updatedBy').not().exists().withMessage('updatedBy is set by the system'),
  body('createdAt').not().exists().withMessage('createdAt is set by the system'),
  body('id').not().exists().withMessage('id is set by the system')
];

const sharedFieldRules = [
  optionalText('middleName', 60, 'Middle name'),
  optionalText('lastName', 60, 'Last name'),
  mobileRule('alternateMobile', 'Alternate mobile', true),
  body('email').optional({ values: 'falsy' }).trim().isEmail().withMessage('A valid email address is required').normalizeEmail(),
  body('dateOfBirth')
    .optional({ values: 'falsy' })
    .isISO8601()
    .withMessage('Date of birth must be a valid date (YYYY-MM-DD)')
    .bail()
    .custom((value) => new Date(value) < new Date())
    .withMessage('Date of birth must be in the past'),
  body('gender').optional({ values: 'falsy' }).isIn(GENDER_VALUES).withMessage(`Gender must be one of: ${GENDER_VALUES.join(', ')}`),
  optionalText('fatherName', 120, "Father's name"),
  optionalText('motherName', 120, "Mother's name"),
  body('maritalStatus')
    .optional({ values: 'falsy' })
    .isIn(MARITAL_STATUS_VALUES)
    .withMessage(`Marital status must be one of: ${MARITAL_STATUS_VALUES.join(', ')}`),
  optionalText('occupation', 120, 'Occupation'),
  optionalText('addressLine1', 255, 'Address line 1'),
  optionalText('addressLine2', 255, 'Address line 2'),
  optionalText('city', 80, 'City'),
  optionalText('state', 80, 'State'),
  body('pincode').optional({ values: 'falsy' }).matches(/^\d{6}$/).withMessage('Pincode must be exactly 6 digits')
];

const createCustomerRules = [
  body('firstName').trim().notEmpty().withMessage('First name is required').bail().isLength({ max: 60 }).withMessage('First name must be at most 60 characters'),
  mobileRule('mobile', 'Mobile', false),
  body('status').optional({ values: 'falsy' }).isIn(CUSTOMER_STATUS_VALUES).withMessage(`Status must be one of: ${CUSTOMER_STATUS_VALUES.join(', ')}`),
  ...sharedFieldRules,
  ...backendControlledRules
];

const updateCustomerRules = [
  idParamRule,
  body('firstName').optional().trim().notEmpty().withMessage('First name cannot be empty').bail().isLength({ max: 60 }).withMessage('First name must be at most 60 characters'),
  mobileRule('mobile', 'Mobile', true),
  // Status has its own endpoint and its own permissions.
  body('status').not().exists().withMessage('Use PATCH /:id/status to change the status'),
  ...sharedFieldRules,
  ...backendControlledRules
];

const changeStatusRules = [
  idParamRule,
  body('status').notEmpty().withMessage('Status is required').bail().isIn(CUSTOMER_STATUS_VALUES).withMessage(`Status must be one of: ${CUSTOMER_STATUS_VALUES.join(', ')}`)
];

const customerIdRules = [idParamRule];

const listCustomersRules = [
  query('page').optional().isInt({ min: 1 }).withMessage('page must be a positive integer'),
  query('limit').optional().isInt({ min: 1, max: 100 }).withMessage('limit must be between 1 and 100'),
  query('search').optional().isString().trim().isLength({ max: 120 }).withMessage('search is too long'),
  query('status').optional().isIn(CUSTOMER_STATUS_VALUES).withMessage(`status must be one of: ${CUSTOMER_STATUS_VALUES.join(', ')}`),
  query('gender').optional().isIn(GENDER_VALUES).withMessage(`gender must be one of: ${GENDER_VALUES.join(', ')}`),
  query('city').optional().isString().trim().isLength({ max: 80 }).withMessage('city is too long'),
  query('state').optional().isString().trim().isLength({ max: 80 }).withMessage('state is too long'),
  query('sortBy')
    .optional()
    .isIn(['fullName', 'cifId', 'city', 'state', 'status', 'createdAt', 'updatedAt'])
    .withMessage('sortBy is not a sortable field'),
  query('sortOrder').optional().isIn(['ASC', 'DESC', 'asc', 'desc']).withMessage('sortOrder must be ASC or DESC')
];

module.exports = {
  createCustomerRules,
  updateCustomerRules,
  changeStatusRules,
  customerIdRules,
  listCustomersRules
};
