'use strict';

const { body, param, query } = require('express-validator');
const {
  LOAN_TYPE_VALUES,
  LOAN_STATUS_VALUES,
  INTEREST_METHOD_VALUES,
  WEEKLY_OFF_VALUES,
  ROI_BASIS_VALUES,
  TENURE_UNIT_VALUES,
  TENURE_UNITS,
  isTenureUnitAllowed,
  usesCollectionCount,
  collectionUnitLabel,
  COLLECTION_COUNT_MIN,
  COLLECTION_COUNT_MAX,
  WEEKLY_OFF,
  LOAN_TYPES,
  isWeeklyOffAllowed,
  ROI_MIN,
  ROI_MAX,
  LOAN_AMOUNT_MIN,
  LOAN_AMOUNT_MAX,
  TENURE_MIN,
  TENURE_MAX
} = require('../config/loans');

const idParamRule = param('id').isInt({ min: 1 }).withMessage('A valid loan id is required');

/**
 * Values the backend derives. Accepting any of them would let a client dictate
 * the loan number or the amount owed, so they are rejected outright rather than
 * silently ignored.
 */
const backendControlledRules = [
  body('loanNumber').not().exists().withMessage('The loan number is generated by the system'),
  body('loan_number').not().exists().withMessage('The loan number is generated by the system'),
  body('totalRepayment').not().exists().withMessage('Total repayment is calculated by the system'),
  body('emiAmount').not().exists().withMessage('EMI amount is calculated by the system'),
  body('emiCount').not().exists().withMessage('EMI count is calculated by the system'),
  body('createdBy').not().exists().withMessage('createdBy is set by the system'),
  body('updatedBy').not().exists().withMessage('updatedBy is set by the system'),
  body('id').not().exists().withMessage('id is set by the system'),
  // The rate basis is a system-wide rule, not a per-request choice: a new loan
  // is always priced on the current one and an existing loan keeps its own.
  body('roiBasis').not().exists().withMessage('The ROI basis is set by the system'),
  body('roi_basis').not().exists().withMessage('The ROI basis is set by the system')
];

const loanAmountRule = (optional) => {
  const chain = optional ? body('loanAmount').optional() : body('loanAmount').exists().withMessage('Loan amount is required').bail();
  return chain
    .isFloat({ min: LOAN_AMOUNT_MIN, max: LOAN_AMOUNT_MAX })
    .withMessage(`Loan amount must be between ${LOAN_AMOUNT_MIN} and ${LOAN_AMOUNT_MAX}`)
    .bail()
    // Rejects "1e5", "Infinity" and values with more than two decimal places.
    .matches(/^\d+(\.\d{1,2})?$/)
    .withMessage('Loan amount must be a plain number with at most 2 decimal places');
};

const roiRule = (optional) => {
  const chain = optional ? body('roi').optional() : body('roi').exists().withMessage('ROI is required').bail();
  return chain
    .isFloat({ min: ROI_MIN, max: ROI_MAX })
    .withMessage(`ROI must be between ${ROI_MIN} and ${ROI_MAX} percent per month`)
    .bail()
    .matches(/^\d+(\.\d{1,4})?$/)
    .withMessage('ROI must be a plain percentage with at most 4 decimal places');
};

const tenureRule = (optional) => {
  const chain = optional ? body('tenure').optional() : body('tenure').exists().withMessage('Tenure is required').bail();
  return chain
    .isInt({ min: TENURE_MIN, max: TENURE_MAX })
    .withMessage(`Tenure must be a whole number between ${TENURE_MIN} and ${TENURE_MAX}`);
};

const loanTypeRule = (optional) => {
  const chain = optional ? body('loanType').optional() : body('loanType').notEmpty().withMessage('Loan type is required').bail();
  return chain.isIn(LOAN_TYPE_VALUES).withMessage(`Loan type must be one of: ${LOAN_TYPE_VALUES.join(', ')}`);
};

const interestMethodRule = () =>
  body('interestMethod')
    .optional()
    .isIn(INTEREST_METHOD_VALUES)
    .withMessage(`Interest method must be one of: ${INTEREST_METHOD_VALUES.join(', ')}`);

const weeklyOffRule = () =>
  body('weeklyOff')
    .optional()
    .isIn(WEEKLY_OFF_VALUES)
    .withMessage(`Weekly off must be one of: ${WEEKLY_OFF_VALUES.join(', ')}`);

/**
 * The one invalid combination: a weekly off on a loan that is not daily.
 * On an update the loan type may be unchanged and therefore absent from the
 * body, so this only rejects what the request itself states.
 */
const weeklyOffCombinationRule = () =>
  body('weeklyOff').custom((value, { req }) => {
    if (!value || value === WEEKLY_OFF.NONE) return true;
    const loanType = req.body.loanType;
    if (loanType !== undefined && !isWeeklyOffAllowed(loanType, value)) {
      throw new Error(`A weekly off can only be set on a ${LOAN_TYPES.DAILY} loan`);
    }
    return true;
  });

/** A daily loan with a weekly off cannot be priced without knowing where it starts. */
const weeklyOffNeedsStartDateRule = () =>
  body('startDate').custom((value, { req }) => {
    if (req.body.weeklyOff && req.body.weeklyOff !== WEEKLY_OFF.NONE && !value) {
      throw new Error('A start date is required when a weekly off is selected');
    }
    return true;
  });

const tenureUnitRule = () =>
  body('tenureUnit')
    .optional()
    .isIn(TENURE_UNIT_VALUES)
    .withMessage(`Tenure unit must be one of: ${TENURE_UNIT_VALUES.join(', ')}`);

/** A month-based tenure is not defined for a weekly loan. */
const tenureUnitCombinationRule = () =>
  body('tenureUnit').custom((value, { req }) => {
    if (!value || value === TENURE_UNITS.PERIODS) return true;
    const loanType = req.body.loanType;
    if (loanType !== undefined && !isTenureUnitAllowed(loanType, value)) {
      throw new Error('This loan type cannot be written as a tenure in months');
    }
    return true;
  });

/** The contractual window of a month-based tenure depends on where it starts. */
const tenureUnitNeedsStartDateRule = () =>
  body('startDate').custom((value, { req }) => {
    if (req.body.tenureUnit === TENURE_UNITS.MONTHS && req.body.loanType !== LOAN_TYPES.MONTHLY && !value) {
      throw new Error('A start date is required when a loan is written in months');
    }
    return true;
  });

/**
 * How many collections repay the contract. A whole number, so "26.5", "0", "-5"
 * and "many" are all refused before anything is priced.
 */
const collectionCountRule = () =>
  body('collectionCount')
    .optional({ values: 'null' })
    .isInt({ min: COLLECTION_COUNT_MIN, max: COLLECTION_COUNT_MAX })
    .withMessage(`The collection count must be a whole number between ${COLLECTION_COUNT_MIN} and ${COLLECTION_COUNT_MAX}`)
    .bail()
    .matches(/^\d+$/)
    .withMessage('The collection count must be a whole number, with no decimal part');

/**
 * It belongs to a loan that collects in days and is written in months. A
 * monthly loan has one collection per contractual month, and a period-based
 * tenure already states the number of collections.
 */
const collectionCountCombinationRule = () =>
  body('collectionCount').custom((value, { req }) => {
    if (value === undefined || value === null || value === '') return true;
    const { loanType, tenureUnit } = req.body;
    if (loanType !== undefined && !usesCollectionCount(loanType, tenureUnit ?? TENURE_UNITS.PERIODS)) {
      throw new Error('A collection count applies only to a daily, weekly or bi-weekly loan whose tenure is in months');
    }
    return true;
  });

/** Such a loan must say how many collections repay it. */
const collectionCountRequiredRule = () =>
  body('collectionCount').custom((value, { req }) => {
    const { loanType, tenureUnit } = req.body;
    if (usesCollectionCount(loanType, tenureUnit) && (value === undefined || value === null || value === '')) {
      throw new Error(`The number of ${collectionUnitLabel(loanType)} is required for a tenure in months`);
    }
    return true;
  });

const startDateRule = (optional) => {
  const chain = optional ? body('startDate').optional() : body('startDate').notEmpty().withMessage('Start date is required').bail();
  return chain.isISO8601().withMessage('Start date must be a valid date (YYYY-MM-DD)');
};

const customerIdListRule = (field, label) =>
  body(field)
    .optional()
    .isArray({ max: 20 })
    .withMessage(`${label} must be an array of up to 20 customer ids`)
    .bail()
    .custom((values) => values.every((value) => Number.isInteger(Number(value)) && Number(value) > 0))
    .withMessage(`${label} must contain positive customer ids`);

const createLoanRules = [
  loanAmountRule(false),
  roiRule(false),
  tenureRule(false),
  loanTypeRule(false),
  startDateRule(false),
  interestMethodRule(),
  weeklyOffRule(),
  weeklyOffCombinationRule(),
  tenureUnitRule(),
  tenureUnitCombinationRule(),
  collectionCountRule(),
  collectionCountCombinationRule(),
  collectionCountRequiredRule(),
  body('applicantCustomerId')
    .exists()
    .withMessage('An applicant is required')
    .bail()
    .isInt({ min: 1 })
    .withMessage('applicantCustomerId must be a positive customer id'),
  customerIdListRule('coApplicantCustomerIds', 'Co-applicants'),
  customerIdListRule('guarantorCustomerIds', 'Guarantors'),
  body('status').not().exists().withMessage('New loans always start as DRAFT'),
  ...backendControlledRules
];

const updateLoanRules = [
  idParamRule,
  loanAmountRule(true),
  roiRule(true),
  tenureRule(true),
  loanTypeRule(true),
  startDateRule(true),
  interestMethodRule(),
  weeklyOffRule(),
  weeklyOffCombinationRule(),
  tenureUnitRule(),
  tenureUnitCombinationRule(),
  collectionCountRule(),
  collectionCountCombinationRule(),
  // Status and parties each have their own endpoint and permissions.
  body('status').not().exists().withMessage('Use PATCH /:id/status to change the status'),
  body('applicantCustomerId').not().exists().withMessage('Use the loan parties endpoints to change parties'),
  body('coApplicantCustomerIds').not().exists().withMessage('Use the loan parties endpoints to change parties'),
  body('guarantorCustomerIds').not().exists().withMessage('Use the loan parties endpoints to change parties'),
  ...backendControlledRules
];

const changeStatusRules = [
  idParamRule,
  body('status')
    .notEmpty()
    .withMessage('Status is required')
    .bail()
    .isIn(LOAN_STATUS_VALUES)
    .withMessage(`Status must be one of: ${LOAN_STATUS_VALUES.join(', ')}`)
];

const loanIdRules = [idParamRule];

const roiBasisRule = () =>
  body('roiBasis')
    .optional()
    .isIn(ROI_BASIS_VALUES)
    .withMessage(`ROI basis must be one of: ${ROI_BASIS_VALUES.join(', ')}`);

const previewRules = [
  loanAmountRule(false),
  roiRule(false),
  tenureRule(false),
  loanTypeRule(false),
  startDateRule(true),
  interestMethodRule(),
  weeklyOffRule(),
  weeklyOffCombinationRule(),
  weeklyOffNeedsStartDateRule(),
  tenureUnitRule(),
  tenureUnitCombinationRule(),
  tenureUnitNeedsStartDateRule(),
  collectionCountRule(),
  collectionCountCombinationRule(),
  // Required here too: a preview that quoted a different instalment count from
  // the one saving would produce is exactly the drift this module avoids.
  collectionCountRequiredRule(),
  roiBasisRule()
];

const listLoansRules = [
  query('page').optional().isInt({ min: 1 }).withMessage('page must be a positive integer'),
  query('limit').optional().isInt({ min: 1, max: 100 }).withMessage('limit must be between 1 and 100'),
  query('search').optional().isString().trim().isLength({ max: 120 }).withMessage('search is too long'),
  query('status').optional().isIn(LOAN_STATUS_VALUES).withMessage(`status must be one of: ${LOAN_STATUS_VALUES.join(', ')}`),
  query('loanType').optional().isIn(LOAN_TYPE_VALUES).withMessage(`loanType must be one of: ${LOAN_TYPE_VALUES.join(', ')}`),
  query('startDateFrom').optional().isISO8601().withMessage('startDateFrom must be a valid date'),
  query('startDateTo').optional().isISO8601().withMessage('startDateTo must be a valid date'),
  query('sortBy')
    .optional()
    .isIn(['loanNumber', 'loanAmount', 'startDate', 'status', 'createdAt', 'updatedAt'])
    .withMessage('sortBy is not a sortable field'),
  query('sortOrder').optional().isIn(['ASC', 'DESC', 'asc', 'desc']).withMessage('sortOrder must be ASC or DESC')
];

module.exports = {
  createLoanRules,
  updateLoanRules,
  changeStatusRules,
  loanIdRules,
  listLoansRules,
  previewRules
};
