'use strict';

const { body, param, query } = require('express-validator');
const { ROUTE_STATUS_VALUES, ASSIGNMENT_STATUS_VALUES } = require('../config/routes');

const idParamRule = param('id').isInt({ min: 1 }).withMessage('A valid route id is required');
const assignmentIdRule = param('assignmentId').isInt({ min: 1 }).withMessage('A valid assignment id is required');

/**
 * Backend-owned fields. Rejecting them turns a silent no-op into a clear 422 —
 * which matters most for routeCode, immutable by design.
 */
const backendControlledRules = [
  body('routeCode').not().exists().withMessage('The route code is generated by the system and cannot be set or changed'),
  body('route_code').not().exists().withMessage('The route code is generated by the system and cannot be set or changed'),
  body('createdBy').not().exists().withMessage('createdBy is set by the system'),
  body('updatedBy').not().exists().withMessage('updatedBy is set by the system'),
  body('id').not().exists().withMessage('id is set by the system')
];

const createRouteRules = [
  body('name').trim().notEmpty().withMessage('Route name is required').bail().isLength({ max: 120 }).withMessage('Route name must be at most 120 characters'),
  body('description').optional({ values: 'falsy' }).isString().withMessage('Description must be text').bail().trim().isLength({ max: 255 }).withMessage('Description must be at most 255 characters'),
  body('status').optional({ values: 'falsy' }).isIn(ROUTE_STATUS_VALUES).withMessage(`Status must be one of: ${ROUTE_STATUS_VALUES.join(', ')}`),
  ...backendControlledRules
];

const updateRouteRules = [
  idParamRule,
  body('name').optional().trim().notEmpty().withMessage('Route name cannot be empty').bail().isLength({ max: 120 }).withMessage('Route name must be at most 120 characters'),
  body('description').optional({ values: 'null' }).isString().withMessage('Description must be text').bail().trim().isLength({ max: 255 }).withMessage('Description must be at most 255 characters'),
  // Status has its own endpoint.
  body('status').not().exists().withMessage('Use PATCH /:id/status to change the status'),
  ...backendControlledRules
];

const changeStatusRules = [
  idParamRule,
  body('status').notEmpty().withMessage('Status is required').bail().isIn(ROUTE_STATUS_VALUES).withMessage(`Status must be one of: ${ROUTE_STATUS_VALUES.join(', ')}`)
];

const assignCollectorRules = [
  idParamRule,
  body('userId').exists().withMessage('A collector is required').bail().isInt({ min: 1 }).withMessage('userId must be a positive integer'),
  body('status').not().exists().withMessage('A new assignment is always ACTIVE'),
  body('assignedAt').not().exists().withMessage('The assignment date is set by the system'),
  body('unassignedAt').not().exists().withMessage('The unassignment date is set by the system')
];

const assignLoanRules = [
  idParamRule,
  body('loanId').exists().withMessage('A loan is required').bail().isInt({ min: 1 }).withMessage('loanId must be a positive integer'),
  body('status').not().exists().withMessage('A new assignment is always ACTIVE'),
  body('assignedAt').not().exists().withMessage('The assignment date is set by the system'),
  body('unassignedAt').not().exists().withMessage('The unassignment date is set by the system')
];

const assignmentStatusRules = [
  idParamRule,
  assignmentIdRule,
  body('status').notEmpty().withMessage('Status is required').bail().isIn(ASSIGNMENT_STATUS_VALUES).withMessage(`Status must be one of: ${ASSIGNMENT_STATUS_VALUES.join(', ')}`)
];

const routeIdRules = [idParamRule];

const listRoutesRules = [
  query('page').optional().isInt({ min: 1 }).withMessage('page must be a positive integer'),
  query('limit').optional().isInt({ min: 1, max: 100 }).withMessage('limit must be between 1 and 100'),
  query('search').optional().isString().trim().isLength({ max: 120 }).withMessage('search is too long'),
  query('status').optional().isIn(ROUTE_STATUS_VALUES).withMessage(`status must be one of: ${ROUTE_STATUS_VALUES.join(', ')}`),
  query('collectorId').optional().isInt({ min: 1 }).withMessage('collectorId must be a positive integer'),
  query('sortBy').optional().isIn(['routeCode', 'name', 'status', 'createdAt', 'updatedAt']).withMessage('sortBy is not a sortable field'),
  query('sortOrder').optional().isIn(['ASC', 'DESC', 'asc', 'desc']).withMessage('sortOrder must be ASC or DESC')
];

const assignmentsRules = [idParamRule, query('includeRemoved').optional().isBoolean().withMessage('includeRemoved must be true or false')];

module.exports = {
  createRouteRules,
  updateRouteRules,
  changeStatusRules,
  assignCollectorRules,
  assignLoanRules,
  assignmentStatusRules,
  routeIdRules,
  listRoutesRules,
  assignmentsRules
};
