'use strict';

const { LEDGER_TYPE_VALUES } = require('./collections');

/**
 * Bulk collection import.
 *
 * Every column is an input the Post Collection endpoint already accepts.
 * Nothing the backend derives — the collection number, the allocation, the EMI
 * it lands on, outstanding, status, DPD, payment dates — appears here, and a
 * file that names one is refused rather than silently ignored.
 *
 * There is deliberately no allocation column: the split across instalments is
 * decided by the existing allocation engine, oldest instalment first.
 */

const MAX_ROWS = 500;
const SHEET_NAME = 'Collections';
const TEMPLATE_FILENAME = 'lms-collection-import-template.xlsx';

const COLUMNS = Object.freeze([
  {
    field: 'loanNumber',
    header: 'Loan Number',
    required: true,
    width: 18,
    example: 'LN26-000002',
    note: 'Required. Must be an existing ACTIVE loan — money cannot be posted to a draft, closed or cancelled loan.'
  },
  {
    field: 'payerCif',
    header: 'Payer CIFID',
    required: true,
    width: 16,
    example: 'C000001',
    note: 'Required. Must be a current party to that loan — applicant, co-applicant or guarantor. Any of them may pay.'
  },
  {
    field: 'amount',
    header: 'Amount',
    required: true,
    width: 14,
    example: '5000.00',
    note: 'Required. Greater than zero, at most 2 decimal places. It must not exceed what the loan still owes.'
  },
  {
    field: 'collectionDate',
    header: 'Collection Date',
    required: true,
    width: 16,
    example: '2026-08-20',
    note: 'Required. YYYY-MM-DD, and not in the future — advance collections are not supported.'
  },
  {
    field: 'ledgerType',
    header: 'Payment Mode',
    required: true,
    width: 14,
    example: 'CASH',
    note: `Required. One of: ${LEDGER_TYPE_VALUES.join(', ')}.`
  },
  {
    field: 'paymentReference',
    header: 'Reference',
    required: false,
    width: 22,
    example: '',
    note: 'Required for BANK collections (UTR or cheque number); optional for cash. Also what distinguishes two payments of the same amount on the same day.'
  },
  {
    field: 'notes',
    header: 'Notes',
    required: false,
    width: 30,
    example: '',
    note: 'Optional, up to 500 characters.'
  }
]);

const normalizeHeader = (value) =>
  String(value ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');

/** Alternative spellings an operator might reasonably use. */
const HEADER_ALIASES = Object.freeze({
  loan: 'loanNumber',
  loanno: 'loanNumber',
  cifid: 'payerCif',
  customercifid: 'payerCif',
  customer: 'payerCif',
  payer: 'payerCif',
  collectionamount: 'amount',
  amountcollected: 'amount',
  date: 'collectionDate',
  paymentdate: 'collectionDate',
  mode: 'ledgerType',
  paymentmode: 'ledgerType',
  ledger: 'ledgerType',
  referenceno: 'paymentReference',
  utr: 'paymentReference',
  chequeno: 'paymentReference',
  remarks: 'notes'
});

const HEADER_TO_FIELD = Object.freeze(
  COLUMNS.reduce(
    (accumulator, column) => {
      accumulator[normalizeHeader(column.header)] = column.field;
      accumulator[normalizeHeader(column.field)] = column.field;
      return accumulator;
    },
    { ...HEADER_ALIASES }
  )
);

/**
 * Everything the backend derives. Named individually so a file that tries to
 * dictate where the money lands gets the real reason.
 *
 * `paymentdate` is deliberately absent: it is an alias for the collection date
 * above, which IS an input. The date an instalment became fully paid is derived
 * from the ledger and is named `emipaymentdate` here.
 */
const BACKEND_OWNED_HEADERS = Object.freeze({
  collectionid: 'The collection id is generated by the system',
  collectionnumber: 'The collection number is generated by the system',
  id: 'The collection id is generated by the system',
  allocatedamount: 'Allocation is performed by the system, oldest instalment first',
  allocation: 'Allocation is performed by the system, oldest instalment first',
  eminumber: 'The instalment a payment lands on is decided by the allocation engine',
  emiid: 'The instalment a payment lands on is decided by the allocation engine',
  emiallocation: 'Allocation is performed by the system, oldest instalment first',
  emistatus: 'EMI status is derived from the allocation ledger',
  emipaymentdate: 'Payment dates are derived from the allocation ledger',
  outstanding: 'Outstanding is derived from the allocation ledger',
  remainingbalance: 'Outstanding is derived from the allocation ledger',
  principaloutstanding: 'The principal/interest split is derived by the system',
  interestoutstanding: 'The principal/interest split is derived by the system',
  dpd: 'DPD is calculated by the system',
  status: 'Collection status is set by the system',
  createdby: 'createdBy is set by the system',
  updatedby: 'updatedBy is set by the system'
});

const ROW_STATUS = Object.freeze({
  VALID: 'VALID',
  INVALID: 'INVALID',
  DUPLICATE: 'DUPLICATE'
});

module.exports = {
  MAX_ROWS,
  SHEET_NAME,
  TEMPLATE_FILENAME,
  COLUMNS,
  HEADER_TO_FIELD,
  BACKEND_OWNED_HEADERS,
  ROW_STATUS
};
