'use strict';

const { GENDER_VALUES, MARITAL_STATUS_VALUES, CUSTOMER_STATUS_VALUES } = require('./customers');

/**
 * Bulk customer import.
 *
 * Every column here is an existing editable field on the customer model — no
 * field is invented for the import, and the backend-owned ones (cifId, fullName,
 * createdBy, timestamps) are deliberately absent. A spreadsheet cannot name
 * them, and a file that tries is refused rather than silently ignored.
 */

const MAX_FILE_BYTES = 2 * 1024 * 1024; // 2 MB
const MAX_ROWS = 500;

/** The worksheet the importer reads. */
const SHEET_NAME = 'Customers';

/**
 * Column definitions, in template order.
 *
 * `field` is the customer attribute; `header` is what the operator sees. The
 * header is matched loosely (case and punctuation are ignored) so a file saved
 * from another tool still lines up, but an unrecognised column is an error.
 */
const COLUMNS = Object.freeze([
  { field: 'firstName', header: 'First Name', required: true, width: 18, example: 'Rahul', note: 'Required.' },
  { field: 'middleName', header: 'Middle Name', required: false, width: 18, example: 'Kumar', note: 'Optional.' },
  { field: 'lastName', header: 'Last Name', required: false, width: 18, example: 'Sharma', note: 'Optional.' },
  {
    field: 'mobile',
    header: 'Mobile',
    required: true,
    width: 16,
    example: '9876543210',
    note: 'Required. Ten digits, starting 6-9. +91 and spaces are accepted. Format the column as Text.'
  },
  {
    field: 'alternateMobile',
    header: 'Alternate Mobile',
    required: false,
    width: 18,
    example: '9812345678',
    note: 'Optional. Same rules as Mobile.'
  },
  { field: 'email', header: 'Email', required: false, width: 26, example: 'rahul.sharma@example.com', note: 'Optional. Must be a valid address.' },
  {
    field: 'dateOfBirth',
    header: 'Date of Birth',
    required: false,
    width: 16,
    example: '1990-05-21',
    note: 'Optional. YYYY-MM-DD, and in the past.'
  },
  { field: 'gender', header: 'Gender', required: false, width: 12, example: 'MALE', note: `Optional. One of: ${GENDER_VALUES.join(', ')}.` },
  { field: 'fatherName', header: "Father's Name", required: false, width: 22, example: 'Suresh Sharma', note: 'Optional.' },
  { field: 'motherName', header: "Mother's Name", required: false, width: 22, example: 'Sunita Sharma', note: 'Optional.' },
  {
    field: 'maritalStatus',
    header: 'Marital Status',
    required: false,
    width: 16,
    example: 'MARRIED',
    note: `Optional. One of: ${MARITAL_STATUS_VALUES.join(', ')}.`
  },
  { field: 'occupation', header: 'Occupation', required: false, width: 20, example: 'Shopkeeper', note: 'Optional.' },
  { field: 'addressLine1', header: 'Address Line 1', required: false, width: 30, example: '12 MG Road', note: 'Optional.' },
  { field: 'addressLine2', header: 'Address Line 2', required: false, width: 30, example: 'Near Bus Stand', note: 'Optional.' },
  { field: 'city', header: 'City', required: false, width: 18, example: 'Pune', note: 'Optional.' },
  { field: 'state', header: 'State', required: false, width: 18, example: 'Maharashtra', note: 'Optional.' },
  {
    field: 'pincode',
    header: 'Pincode',
    required: false,
    width: 12,
    example: '411001',
    note: 'Optional. Exactly 6 digits. Format the column as Text so a leading zero survives.'
  },
  {
    field: 'status',
    header: 'Status',
    required: false,
    width: 12,
    example: 'ACTIVE',
    note: `Optional, defaults to ACTIVE. One of: ${CUSTOMER_STATUS_VALUES.join(', ')}.`
  }
]);

const REQUIRED_COLUMNS = Object.freeze(COLUMNS.filter((column) => column.required).map((column) => column.field));

/** Loose header matching: "First Name", "firstName" and "first_name" all agree. */
const normalizeHeader = (value) =>
  String(value ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');

const HEADER_TO_FIELD = Object.freeze(
  COLUMNS.reduce((accumulator, column) => {
    accumulator[normalizeHeader(column.header)] = column.field;
    accumulator[normalizeHeader(column.field)] = column.field;
    return accumulator;
  }, {})
);

/**
 * Headers that name something the backend owns. They are called out by name so
 * the operator gets the real reason rather than a generic "unknown column".
 */
const BACKEND_OWNED_HEADERS = Object.freeze({
  cifid: 'CIFID is generated by the system and cannot come from a spreadsheet',
  cif: 'CIFID is generated by the system and cannot come from a spreadsheet',
  customerid: 'The customer id is generated by the system',
  id: 'The customer id is generated by the system',
  fullname: 'Full name is derived from the name fields',
  createdby: 'createdBy is set by the system',
  updatedby: 'updatedBy is set by the system',
  createdat: 'createdAt is set by the system',
  updatedat: 'updatedAt is set by the system'
});

/** Row outcomes reported by the preview and the import. */
const ROW_STATUS = Object.freeze({
  VALID: 'VALID',
  INVALID: 'INVALID',
  DUPLICATE: 'DUPLICATE'
});

const TEMPLATE_FILENAME = 'lms-customer-import-template.xlsx';

const ACCEPTED_EXTENSIONS = Object.freeze(['.xlsx']);

/** The MIME types browsers and Excel actually send for a .xlsx file. */
const ACCEPTED_MIME_TYPES = Object.freeze([
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/octet-stream'
]);

/** Every .xlsx is a ZIP container, so it must start with the ZIP magic bytes. */
const ZIP_MAGIC = Buffer.from([0x50, 0x4b, 0x03, 0x04]);

module.exports = {
  MAX_FILE_BYTES,
  MAX_ROWS,
  SHEET_NAME,
  COLUMNS,
  REQUIRED_COLUMNS,
  HEADER_TO_FIELD,
  BACKEND_OWNED_HEADERS,
  ROW_STATUS,
  TEMPLATE_FILENAME,
  ACCEPTED_EXTENSIONS,
  ACCEPTED_MIME_TYPES,
  ZIP_MAGIC,
  normalizeHeader
};
