'use strict';

const {
  LOAN_TYPE_VALUES,
  INTEREST_METHOD_VALUES,
  TENURE_UNIT_VALUES,
  WEEKLY_OFF_VALUES,
  ROI_MIN,
  ROI_MAX,
  LOAN_AMOUNT_MIN,
  TENURE_MIN,
  TENURE_MAX
} = require('./loans');

/**
 * Bulk loan import.
 *
 * Every column is an input TERM the loan form already accepts. Nothing the
 * backend derives — the loan number, interest, total repayment, EMI amount, EMI
 * count, the schedule, DPD, collected amounts — appears here, and a file that
 * names one is refused rather than silently ignored.
 */

const MAX_ROWS = 200;
const SHEET_NAME = 'Loans';
const TEMPLATE_FILENAME = 'lms-loan-import-template.xlsx';

/** Several CIFIDs in one cell: "C000002, C000003". */
const CIF_LIST_SEPARATOR = /[,;/|]+/;

const COLUMNS = Object.freeze([
  {
    field: 'applicantCif',
    header: 'Applicant CIFID',
    required: true,
    width: 18,
    example: 'C000001',
    note: 'Required. Must be an existing, active customer. Exactly one applicant per loan.'
  },
  {
    field: 'coApplicantCifs',
    header: 'Co-applicant CIFIDs',
    required: false,
    width: 24,
    example: '',
    note: 'Optional. One or more existing CIFIDs, separated by commas. A customer may hold only one role on a loan.'
  },
  {
    field: 'guarantorCifs',
    header: 'Guarantor CIFIDs',
    required: false,
    width: 24,
    example: '',
    note: 'Optional. Same rules as co-applicants.'
  },
  {
    field: 'loanAmount',
    header: 'Loan Amount',
    required: true,
    width: 16,
    example: '100000.00',
    note: `Required. The principal, at least ${LOAN_AMOUNT_MIN}, with at most 2 decimal places.`
  },
  {
    field: 'roi',
    header: 'ROI % per month',
    required: true,
    width: 16,
    example: '5',
    note: `Required. A MONTHLY rate: 5 means 5% per month. Between ${ROI_MIN} and ${ROI_MAX}, at most 4 decimal places.`
  },
  {
    field: 'interestMethod',
    header: 'ROI Method',
    required: false,
    width: 14,
    example: 'FLAT',
    note: `Optional, defaults to FLAT. One of: ${INTEREST_METHOD_VALUES.join(', ')}.`
  },
  {
    field: 'loanType',
    header: 'Loan Type',
    required: true,
    width: 14,
    example: 'WEEKLY',
    note: `Required. One of: ${LOAN_TYPE_VALUES.join(', ')}.`
  },
  {
    field: 'tenure',
    header: 'Tenure',
    required: true,
    width: 12,
    example: '6',
    note: `Required. A whole number between ${TENURE_MIN} and ${TENURE_MAX}, counted in the Tenure Unit.`
  },
  {
    field: 'tenureUnit',
    header: 'Tenure Unit',
    required: false,
    width: 14,
    example: 'MONTHS',
    note:
      `Optional, defaults to PERIODS. One of: ${TENURE_UNIT_VALUES.join(', ')}. ` +
      'PERIODS counts the loan type\'s own periods; MONTHS makes it a contract of calendar months.'
  },
  {
    field: 'collectionCount',
    header: 'Collection Count',
    required: false,
    width: 18,
    example: '26',
    note:
      'Required for a DAILY, WEEKLY or BI_WEEKLY loan whose tenure is in MONTHS — how many collections repay it ' +
      '(days, weeks or fortnights). Must fit inside the contractual period. Leave blank for a MONTHLY loan.'
  },
  {
    field: 'weeklyOff',
    header: 'Weekly Off',
    required: false,
    width: 14,
    example: 'NONE',
    note: `Optional, defaults to NONE. One of: ${WEEKLY_OFF_VALUES.join(', ')}. Only a DAILY loan may have one.`
  },
  {
    field: 'startDate',
    header: 'Start Date',
    required: true,
    width: 14,
    example: '2026-08-20',
    note: 'Required. YYYY-MM-DD. The contractual period runs from this date.'
  }
]);

const normalizeHeader = (value) =>
  String(value ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');

/** Alternative spellings an operator might reasonably use. */
const HEADER_ALIASES = Object.freeze({
  cifid: 'applicantCif',
  applicant: 'applicantCif',
  coapplicant: 'coApplicantCifs',
  coapplicants: 'coApplicantCifs',
  guarantor: 'guarantorCifs',
  guarantors: 'guarantorCifs',
  amount: 'loanAmount',
  principal: 'loanAmount',
  roipermonth: 'roi',
  interestmethod: 'interestMethod',
  roimethod: 'interestMethod',
  numberofdays: 'collectionCount',
  numberofweeks: 'collectionCount',
  numberofbiweeklycollections: 'collectionCount'
});

const HEADER_TO_FIELD = Object.freeze(
  COLUMNS.reduce(
    (accumulator, column) => {
      accumulator[normalizeHeader(column.header)] = column.field;
      accumulator[normalizeHeader(column.field)] = column.field;
      return accumulator;
    },
    { ...HEADER_ALIASES }
  )
);

/**
 * Everything the backend derives. Named individually so a file that tries to
 * dictate the money gets the real reason.
 */
const BACKEND_OWNED_HEADERS = Object.freeze({
  loannumber: 'The loan number is generated by the system',
  loanid: 'The loan id is generated by the system',
  id: 'The loan id is generated by the system',
  interest: 'Interest is calculated by the system from the terms',
  totalinterest: 'Interest is calculated by the system from the terms',
  totalrepayment: 'Total repayment is calculated by the system',
  emiamount: 'The EMI amount is calculated by the system',
  emicount: 'The EMI count is calculated by the system',
  emidate: 'EMI dates are generated by the schedule service',
  principal: 'The principal/interest split is calculated by the system',
  outstanding: 'Outstanding is derived from the allocation ledger',
  dpd: 'DPD is calculated by the system',
  status: 'Loan status is set by the system',
  amountcollected: 'Collected amounts are derived from the allocation ledger',
  roibasis: 'The ROI basis is set by the system',
  createdby: 'createdBy is set by the system',
  updatedby: 'updatedBy is set by the system'
});

const ROW_STATUS = Object.freeze({
  VALID: 'VALID',
  INVALID: 'INVALID',
  DUPLICATE: 'DUPLICATE'
});

module.exports = {
  MAX_ROWS,
  SHEET_NAME,
  TEMPLATE_FILENAME,
  CIF_LIST_SEPARATOR,
  COLUMNS,
  HEADER_TO_FIELD,
  BACKEND_OWNED_HEADERS,
  ROW_STATUS
};
