'use strict';

/*
 * TEMPORARY: oneBulk historical collection migration utility.
 * Can be removed after historical collections are migrated.
 *
 * This file is intentionally standalone — it does not import from
 * `config/collectionImport.js` and nothing outside `oneBulk*` files imports
 * from here. Deleting every `oneBulk*` file, this one included, and the two
 * lines that mount its route and its nav entry, removes the feature cleanly.
 */

const { LEDGER_TYPE_VALUES } = require('./collections');

const MAX_ROWS = 1000;
const SHEET_NAME = 'OneBulk';
const TEMPLATE_FILENAME = 'lms-one-bulk-import-template.xlsx';

/**
 * Same shape as a normal collection posting — loan, payer, amount, date, mode,
 * an optional reference and note. Nothing here is derived: the allocation
 * across instalments is planned by the existing FIFO engine, exactly as the
 * permanent collection import does.
 */
const COLUMNS = Object.freeze([
  {
    field: 'loanNumber',
    header: 'Loan Number',
    required: true,
    width: 18,
    example: 'LN26-000002',
    note: 'Required. Must be an existing ACTIVE loan, using its CURRENT loan number.'
  },
  {
    field: 'payerCif',
    header: 'Payer CIFID',
    required: true,
    width: 16,
    example: 'C000001',
    note: 'Required. Must be a current party to that loan — applicant, co-applicant or guarantor.'
  },
  {
    field: 'amount',
    header: 'Amount',
    required: true,
    width: 14,
    example: '5000.00',
    note: 'Required. Greater than zero, at most 2 decimal places.'
  },
  {
    field: 'collectionDate',
    header: 'Collection Date',
    required: true,
    width: 16,
    example: '2026-08-20',
    note:
      'Required. YYYY-MM-DD, and not in the future. Rows for the same loan are applied in date order regardless ' +
      'of where they sit in the file, oldest first; rows on the same date keep their file order.'
  },
  {
    field: 'ledgerType',
    header: 'Payment Mode',
    required: true,
    width: 14,
    example: 'CASH',
    note: `Required. One of: ${LEDGER_TYPE_VALUES.join(', ')}.`
  },
  {
    field: 'paymentReference',
    header: 'Reference',
    required: false,
    width: 22,
    example: '',
    note: 'Required for BANK payments; optional for cash. Also what tells two same-day, same-amount payments apart.'
  },
  {
    field: 'notes',
    header: 'Notes',
    required: false,
    width: 30,
    example: '',
    note: 'Optional, up to 500 characters.'
  }
]);

const normalizeHeader = (value) =>
  String(value ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');

const HEADER_ALIASES = Object.freeze({
  loan: 'loanNumber',
  loanno: 'loanNumber',
  cifid: 'payerCif',
  customercifid: 'payerCif',
  customer: 'payerCif',
  payer: 'payerCif',
  collectionamount: 'amount',
  amountcollected: 'amount',
  date: 'collectionDate',
  paymentdate: 'collectionDate',
  mode: 'ledgerType',
  paymentmode: 'ledgerType',
  ledger: 'ledgerType',
  referenceno: 'paymentReference',
  utr: 'paymentReference',
  chequeno: 'paymentReference',
  remarks: 'notes'
});

const HEADER_TO_FIELD = Object.freeze(
  COLUMNS.reduce(
    (accumulator, column) => {
      accumulator[normalizeHeader(column.header)] = column.field;
      accumulator[normalizeHeader(column.field)] = column.field;
      return accumulator;
    },
    { ...HEADER_ALIASES }
  )
);

/** Everything the backend derives — a file that tries to dictate one is refused. */
const BACKEND_OWNED_HEADERS = Object.freeze({
  collectionid: 'The collection id is generated by the system',
  collectionnumber: 'The collection number is generated by the system',
  id: 'The collection id is generated by the system',
  allocatedamount: 'Allocation is performed by the system, oldest instalment first',
  allocation: 'Allocation is performed by the system, oldest instalment first',
  eminumber: 'The instalment a payment lands on is decided by the allocation engine',
  emiid: 'The instalment a payment lands on is decided by the allocation engine',
  emistatus: 'EMI status is derived from the allocation ledger',
  emipaymentdate: 'Payment dates are derived from the allocation ledger',
  outstanding: 'Outstanding is derived from the allocation ledger',
  remainingbalance: 'Outstanding is derived from the allocation ledger',
  dpd: 'DPD is calculated by the system',
  status: 'Collection status is set by the system',
  createdby: 'createdBy is set by the system',
  updatedby: 'updatedBy is set by the system'
});

const ROW_STATUS = Object.freeze({
  VALID: 'VALID',
  INVALID: 'INVALID',
  DUPLICATE: 'DUPLICATE'
});

module.exports = {
  MAX_ROWS,
  SHEET_NAME,
  TEMPLATE_FILENAME,
  COLUMNS,
  HEADER_TO_FIELD,
  BACKEND_OWNED_HEADERS,
  ROW_STATUS
};
