'use strict';

const { ROLES } = require('./roles');

/**
 * Permission catalogue.
 *
 * Identifiers are `<module>.<action>`. Future modules add their own entries here
 * (e.g. `customers.view`, `loans.create`) and the seed grants them — no schema or
 * middleware change is needed to introduce a new permission.
 */
const PERMISSIONS = Object.freeze({
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_ACTIVATE: 'users.activate',
  USERS_DEACTIVATE: 'users.deactivate',
  USERS_ASSIGN_ROLE: 'users.assign_role',
  USERS_RESET_PASSWORD: 'users.reset_password',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  PERMISSIONS_VIEW: 'permissions.view',
  PERMISSIONS_MANAGE: 'permissions.manage',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CUSTOMERS_ACTIVATE: 'customers.activate',
  CUSTOMERS_DEACTIVATE: 'customers.deactivate',
  CUSTOMERS_IMPORT: 'customers.import',
  LOAN_PARTIES_VIEW: 'loan_parties.view',
  LOAN_PARTIES_CREATE: 'loan_parties.create',
  LOAN_PARTIES_UPDATE: 'loan_parties.update',
  LOAN_PARTIES_REMOVE: 'loan_parties.remove',
  LOAN_PARTIES_SWAP: 'loan_parties.swap',
  LOANS_VIEW: 'loans.view',
  LOANS_CREATE: 'loans.create',
  LOANS_UPDATE: 'loans.update',
  LOANS_ACTIVATE: 'loans.activate',
  LOANS_CLOSE: 'loans.close',
  LOANS_CANCEL: 'loans.cancel',
  LOANS_IMPORT: 'loans.import',
  EMIS_VIEW: 'emis.view',
  EMIS_GENERATE: 'emis.generate',
  EMIS_UPDATE: 'emis.update',
  EMIS_BOUNCE_CHARGE: 'emis.bounce_charge',
  COLLECTIONS_VIEW: 'collections.view',
  COLLECTIONS_CREATE: 'collections.create',
  COLLECTIONS_REVERSE: 'collections.reverse',
  COLLECTIONS_IMPORT: 'collections.import',
  ROUTES_VIEW: 'routes.view',
  ROUTES_CREATE: 'routes.create',
  ROUTES_UPDATE: 'routes.update',
  ROUTES_ASSIGN: 'routes.assign',
  DEMAND_VIEW: 'demand.view',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  RECEIPTS_VIEW: 'receipts.view',
  DASHBOARD_VIEW: 'dashboard.view'
});

/** Every permission that exists, with the description stored in the table. */
const PERMISSION_DEFINITIONS = [
  { name: PERMISSIONS.USERS_VIEW, description: 'View the user list and user details' },
  { name: PERMISSIONS.USERS_CREATE, description: 'Create new users' },
  { name: PERMISSIONS.USERS_UPDATE, description: 'Edit user name, email and status' },
  { name: PERMISSIONS.USERS_DELETE, description: 'Delete users (reserved — deletion is disabled in Phase 2)' },
  { name: PERMISSIONS.USERS_ACTIVATE, description: 'Activate a deactivated user' },
  { name: PERMISSIONS.USERS_DEACTIVATE, description: 'Deactivate an active user' },
  { name: PERMISSIONS.USERS_ASSIGN_ROLE, description: "Change a user's role" },
  { name: PERMISSIONS.USERS_RESET_PASSWORD, description: "Reset another user's password" },
  { name: PERMISSIONS.ROLES_VIEW, description: 'View roles and their permissions' },
  { name: PERMISSIONS.ROLES_MANAGE, description: 'Change which permissions a role holds' },
  { name: PERMISSIONS.PERMISSIONS_VIEW, description: 'View the permission catalogue' },
  { name: PERMISSIONS.PERMISSIONS_MANAGE, description: 'Manage the permission catalogue' },
  { name: PERMISSIONS.CUSTOMERS_VIEW, description: 'View the customer list and customer details' },
  { name: PERMISSIONS.CUSTOMERS_CREATE, description: 'Create customers (CIFID is generated by the system)' },
  { name: PERMISSIONS.CUSTOMERS_UPDATE, description: 'Edit customer details' },
  { name: PERMISSIONS.CUSTOMERS_ACTIVATE, description: 'Reactivate an inactive customer' },
  { name: PERMISSIONS.CUSTOMERS_DEACTIVATE, description: 'Deactivate an active customer' },
  {
    name: PERMISSIONS.CUSTOMERS_IMPORT,
    description: 'Bulk-import customers from a spreadsheet (CIFIDs are still generated by the system)'
  },
  { name: PERMISSIONS.LOAN_PARTIES_VIEW, description: 'View the parties attached to a loan' },
  { name: PERMISSIONS.LOAN_PARTIES_CREATE, description: 'Attach a customer to a loan as applicant, co-applicant or guarantor' },
  { name: PERMISSIONS.LOAN_PARTIES_UPDATE, description: "Change a party's role on a loan" },
  { name: PERMISSIONS.LOAN_PARTIES_REMOVE, description: 'Remove a party from a loan (soft removal, history preserved)' },
  { name: PERMISSIONS.LOAN_PARTIES_SWAP, description: 'Swap the applicant and a co-applicant on a loan' },
  { name: PERMISSIONS.LOANS_VIEW, description: 'View loans and loan details' },
  { name: PERMISSIONS.LOANS_CREATE, description: 'Create loans (loan number and financials are generated by the system)' },
  { name: PERMISSIONS.LOANS_UPDATE, description: 'Edit the terms of a draft loan' },
  { name: PERMISSIONS.LOANS_ACTIVATE, description: 'Activate a draft loan' },
  { name: PERMISSIONS.LOANS_CLOSE, description: 'Close an active loan' },
  { name: PERMISSIONS.LOANS_CANCEL, description: 'Cancel a draft or active loan' },
  {
    name: PERMISSIONS.LOANS_IMPORT,
    description: 'Bulk-import loans from a spreadsheet (all figures are still calculated by the system)'
  },
  { name: PERMISSIONS.EMIS_VIEW, description: 'View a loan EMI schedule' },
  { name: PERMISSIONS.EMIS_GENERATE, description: 'Generate a missing EMI schedule for an active loan' },
  { name: PERMISSIONS.EMIS_UPDATE, description: 'Recalculate stored DPD and status snapshots on a schedule' },
  { name: PERMISSIONS.EMIS_BOUNCE_CHARGE, description: 'Record or amend the manual bounce charge on an instalment' },
  { name: PERMISSIONS.COLLECTIONS_VIEW, description: 'View collections and their allocations' },
  { name: PERMISSIONS.COLLECTIONS_CREATE, description: 'Post a collection against a loan' },
  { name: PERMISSIONS.COLLECTIONS_REVERSE, description: 'Reverse a posted collection' },
  {
    name: PERMISSIONS.COLLECTIONS_IMPORT,
    description: 'Bulk-import collections from a spreadsheet (allocation is still performed by the system)'
  },
  { name: PERMISSIONS.ROUTES_VIEW, description: 'View collection routes (a collector sees only their own)' },
  { name: PERMISSIONS.ROUTES_CREATE, description: 'Create collection routes' },
  { name: PERMISSIONS.ROUTES_UPDATE, description: 'Edit a route and change its status' },
  { name: PERMISSIONS.ROUTES_ASSIGN, description: 'Assign collectors and loans to routes' },
  { name: PERMISSIONS.DEMAND_VIEW, description: 'View collection demand (a collector sees only their own routes)' },
  { name: PERMISSIONS.REPORTS_VIEW, description: 'View reports (a collector sees only their own routes)' },
  { name: PERMISSIONS.REPORTS_EXPORT, description: 'Download report data as CSV' },
  { name: PERMISSIONS.RECEIPTS_VIEW, description: 'View a collection receipt' },
  { name: PERMISSIONS.DASHBOARD_VIEW, description: 'View the operational dashboard (a collector sees only their own routes)' }
];

const ROLE_DEFINITIONS = [
  { name: ROLES.SUPER_ADMIN, description: 'Full system access, including permission management' },
  { name: ROLES.ADMIN, description: 'Administrative access to users and operational modules' },
  { name: ROLES.MANAGER, description: 'Operational management and reporting' },
  { name: ROLES.COLLECTOR, description: 'Field collection duties' },
  { name: ROLES.STAFF, description: 'Basic operational access' }
];

/** `'*'` means "every permission that exists", re-evaluated on each seed run. */
const ALL_PERMISSIONS = '*';

const ROLE_PERMISSION_MATRIX = Object.freeze({
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.USERS_ASSIGN_ROLE,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.CUSTOMERS_ACTIVATE,
    PERMISSIONS.CUSTOMERS_DEACTIVATE,
    PERMISSIONS.CUSTOMERS_IMPORT,
    PERMISSIONS.LOAN_PARTIES_VIEW,
    PERMISSIONS.LOAN_PARTIES_CREATE,
    PERMISSIONS.LOAN_PARTIES_UPDATE,
    PERMISSIONS.LOAN_PARTIES_REMOVE,
    PERMISSIONS.LOAN_PARTIES_SWAP,
    PERMISSIONS.LOANS_VIEW,
    PERMISSIONS.LOANS_CREATE,
    PERMISSIONS.LOANS_UPDATE,
    PERMISSIONS.LOANS_ACTIVATE,
    PERMISSIONS.LOANS_CLOSE,
    PERMISSIONS.LOANS_CANCEL,
    PERMISSIONS.LOANS_IMPORT,
    PERMISSIONS.EMIS_VIEW,
    PERMISSIONS.EMIS_GENERATE,
    PERMISSIONS.EMIS_UPDATE,
    // Recording a fee by hand is an administrative act, so it sits with ADMIN
    // and SUPER_ADMIN — the same reach as the DPD recalculation above, and
    // deliberately not with MANAGER, COLLECTOR or STAFF.
    PERMISSIONS.EMIS_BOUNCE_CHARGE,
    PERMISSIONS.COLLECTIONS_VIEW,
    PERMISSIONS.COLLECTIONS_CREATE,
    PERMISSIONS.COLLECTIONS_REVERSE,
    PERMISSIONS.COLLECTIONS_IMPORT,
    PERMISSIONS.ROUTES_VIEW,
    PERMISSIONS.ROUTES_CREATE,
    PERMISSIONS.ROUTES_UPDATE,
    PERMISSIONS.ROUTES_ASSIGN,
    PERMISSIONS.DEMAND_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.RECEIPTS_VIEW,
    PERMISSIONS.DASHBOARD_VIEW
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.LOAN_PARTIES_VIEW,
    PERMISSIONS.LOAN_PARTIES_CREATE,
    PERMISSIONS.LOAN_PARTIES_UPDATE,
    PERMISSIONS.LOANS_VIEW,
    PERMISSIONS.LOANS_CREATE,
    PERMISSIONS.LOANS_UPDATE,
    PERMISSIONS.LOANS_ACTIVATE,
    PERMISSIONS.LOANS_CLOSE,
    PERMISSIONS.LOANS_CANCEL,
    PERMISSIONS.LOANS_IMPORT,
    PERMISSIONS.EMIS_VIEW,
    PERMISSIONS.EMIS_GENERATE,
    PERMISSIONS.COLLECTIONS_VIEW,
    PERMISSIONS.COLLECTIONS_CREATE,
    PERMISSIONS.COLLECTIONS_REVERSE,
    PERMISSIONS.COLLECTIONS_IMPORT,
    PERMISSIONS.ROUTES_VIEW,
    PERMISSIONS.ROUTES_CREATE,
    PERMISSIONS.ROUTES_UPDATE,
    PERMISSIONS.ROUTES_ASSIGN,
    PERMISSIONS.DEMAND_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.RECEIPTS_VIEW,
    PERMISSIONS.DASHBOARD_VIEW
  ],
  // A collector takes money but cannot undo a posting — reversal is a
  // supervisory action and is deliberately withheld. Route and demand access is
  // read-only and scoped by the service to the routes they are assigned to;
  // they can neither create routes nor assign anyone.
  [ROLES.COLLECTOR]: [
    PERMISSIONS.LOAN_PARTIES_VIEW,
    PERMISSIONS.LOANS_VIEW,
    PERMISSIONS.EMIS_VIEW,
    PERMISSIONS.COLLECTIONS_VIEW,
    PERMISSIONS.COLLECTIONS_CREATE,
    PERMISSIONS.ROUTES_VIEW,
    PERMISSIONS.DEMAND_VIEW,
    // Reports and receipts are read-only and scoped by the service to the
    // collector's own routes. Export is withheld: a downloaded file leaves the
    // system's access controls behind, so it stays a supervisory action.
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.RECEIPTS_VIEW,
    // Scoped by the service to their own routes, same as reports and demand.
    PERMISSIONS.DASHBOARD_VIEW
  ],
  [ROLES.STAFF]: []
});

module.exports = {
  PERMISSIONS,
  PERMISSION_DEFINITIONS,
  ROLE_DEFINITIONS,
  ROLE_PERMISSION_MATRIX,
  ALL_PERMISSIONS
};
